### ISSUE TITLE
Duration./ truncates

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/base#180] opened 2023-10-12 21:35 UTC
`Duration.second / +2` gives `0` rather than `+500 * millisecond`

**Comment by gfinol** [comment] 2023-10-22 19:04
Hi,
We have been solving this issue in the Unison discord. 

I think that the issue is solved in this branch:
[@gfinol/duration-truncation](https://share.unison-lang.org/@unison/base/code/@gfinol/duration-truncation/latest)

**Comment by runarorama** [comment] 2023-10-30 00:09
This is merged into `main`. Thank you! 🌈⭐

**Closed as completed by runarorama** 2023-10-30 00:09 UTC
