### ISSUE TITLE
Add arbitrary-precision Natural numbers 

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base#24] opened 2021-07-16 18:22 UTC
This adds the `Natural` type, operations on that type, and a few supporting operations to Base. This type provides arbitrary-precision arithmetic on positive integers, letting users work with very large numbers as well as paving the way for supporting exact fractions and rational numbers.

Operations here are not nearly as fast as they could be, as the underlying type is a `List`. Once we have a more suitable data type in Unison, the representation here should be easy to replace.

  The changes summarized below are available for you to review, using the following
  command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/bv2:.arbprecnats

  Added definitions:

     unique type Natural (+2 metadata)
     Natural.internal.Natural                : Nonempty Nat -> Natural
     Abort.abortWhen                         : Boolean ->{Abort} () (+2 metadata)
     Abort.abortWhen.doc                     : Doc (+2 metadata)
     Abort.toBug                             : '{g, Abort} a ->{g} a (+2 metadata)
     Abort.toBug.doc                         : Doc (+2 metadata)
     Char.ascii.fromBase36Digit              : Nat -> Optional Char (+2 metadata)
     Char.ascii.fromBase36Digit.doc          : Doc (+2 metadata)
     Char.ascii.toBase36Digit                : Char -> Optional Nat (+2 metadata)
     Char.ascii.toBase36Digit.doc            : Doc (+2 metadata)
     Int.!=                                  : Int -> Int -> Boolean (+2 metadata)
     Int.max                                 : Int -> Int -> Int (+2 metadata)
     Int.min                                 : Int -> Int -> Int (+2 metadata)
     Int.mod.test                            : [Result] (+3 metadata)
     List.Nonempty.appendList                : Nonempty a
                                             -> [a]
                                             -> Nonempty a (+2 metadata)
     List.Nonempty.appendList.doc            : Doc (+2 metadata)
     List.Nonempty.reverse                   : Nonempty a -> Nonempty a (+2 metadata)
     List.Nonempty.reverse.doc               : Doc (+2 metadata)
     List.dropRightWhile                     : (a ->{g} Boolean)
                                             -> [a]
                                             ->{g} [a] (+2 metadata)
     List.dropRightWhile.doc                 : Doc (+2 metadata)
     List.slidingPairs                       : [a] -> [(a, a)] (+2 metadata)
     List.slidingPairs.doc                   : Doc (+2 metadata)
     List.slidingPairs.tests.concat          : [Result] (+3 metadata)
     List.updateAt                           : (a ->{g} a)
                                             -> Nat
                                             -> [a]
                                             ->{g} [a] (+2 metadata)
     List.updateAt.doc                       : Doc (+2 metadata)
     List.updateAt.tests.updates             : [Result] (+3 metadata)
     Nat.!=                                  : Nat -> Nat -> Boolean (+2 metadata)
     Nat.max                                 : Nat -> Nat -> Nat (+2 metadata)
     Nat.min                                 : Nat -> Nat -> Nat (+2 metadata)
     Natural.*                               : Natural
                                             -> Natural
                                             -> Natural (+3 metadata)
     Natural.+                               : Natural
                                             -> Natural
                                             -> Natural (+3 metadata)
     Natural.-                               : Natural
                                             -> Natural
                                             -> Natural (+3 metadata)
     ┌ Natural./                             : Natural
                                             -> Natural
                                             -> Optional Natural (+2 metadata)
     └ Natural.div                           : Natural
                                             -> Natural
                                             -> Optional Natural (+2 metadata)
     ┌ Natural.<                             : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     └ Natural.lt                            : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     ┌ Natural.<=                            : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     └ Natural.lteq                          : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     ┌ Natural.==                            : Natural
                                             -> Natural
                                             -> Boolean (+2 metadata)
     └ Natural.eq                            : Natural
                                             -> Natural
                                             -> Boolean (+2 metadata)
     ┌ Natural.>                             : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     └ Natural.gt                            : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     ┌ Natural.>=                            : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     └ Natural.gteq                          : Natural
                                             -> Natural
                                             -> Boolean (+3 metadata)
     ┌ Natural.^                             : Natural -> Nat -> Natural (+2 metadata)
     └ Natural.pow                           : Natural -> Nat -> Natural (+2 metadata)
     Natural.div!                            : Natural
                                             -> Natural
                                             ->{Abort} Natural (+2 metadata)
     Natural.divMod                          : Natural
                                             -> Natural
                                             -> Optional (Natural, Natural) (+2 metadata)
     Natural.divMod!                         : Natural
                                             -> Natural
                                             ->{Abort} (Natural, Natural) (+3 metadata)
     Natural.doc                             : Doc (+2 metadata)
     Natural.docs.arithmetic                 : Doc (+2 metadata)
     Natural.docs.constructing               : Doc (+2 metadata)
     Natural.docs.converting                 : Doc (+2 metadata)
     Natural.docs.relations                  : Doc (+2 metadata)
     Natural.fromNat                         : Nat -> Natural (+3 metadata)
     Natural.fromNat.doc                     : Doc (+2 metadata)
     Natural.internal.bitMask                : Nat (+3 metadata)
     Natural.internal.bitWidth               : Nat (+2 metadata)
     Natural.internal.digits                 : Natural -> Nonempty Nat (+2 metadata)
     Natural.internal.divImpl                : Natural
                                             -> Natural
                                             ->{Abort} (Natural, Natural) (+2 metadata)
     Natural.internal.fromNats               : [Nat] -> Natural (+3 metadata)
     Natural.internal.mkNatural              : [Nat] -> Natural (+2 metadata)
     Natural.internal.normalize              : Natural -> Natural (+3 metadata)
     Natural.internal.radix                  : Nat (+3 metadata)
     Natural.isZero                          : Natural -> Boolean (+2 metadata)
     Natural.isZero.doc                      : Doc (+2 metadata)
     Natural.mod                             : Natural
                                             -> Natural
                                             -> Optional Natural (+2 metadata)
     Natural.mod!                            : Natural
                                             -> Natural
                                             ->{Abort} Natural (+2 metadata)
     Natural.mod!.doc                        : Doc (+2 metadata)
     Natural.mod.doc                         : Doc (+2 metadata)
     Natural.one                             : Natural (+3 metadata)
     Natural.one.doc                         : Doc (+2 metadata)
     Natural.parse                           : Text
                                             -> Nat
                                             -> Optional Natural (+3 metadata)
     Natural.parse!                          : Text
                                             -> Nat
                                             ->{Abort} Natural (+3 metadata)
     Natural.parse!.doc                      : Doc (+2 metadata)
     Natural.parse!.tests.roundtrip          : [Result] (+3 metadata)
     Natural.parse.doc                       : Doc (+2 metadata)
     Natural.parse.tests.roundtrip           : [Result] (+3 metadata)
     Natural.pow.tests.powerOfOne            : [Result] (+3 metadata)
     Natural.pow.tests.powerOfPower          : [Result] (+3 metadata)
     Natural.pow.tests.powerOfProduct        : [Result] (+3 metadata)
     Natural.pow.tests.powerOfZero           : [Result] (+3 metadata)
     Natural.pow.tests.product               : [Result] (+3 metadata)
     Natural.pow.tests.quotient              : [Result] (+3 metadata)
     Natural.tests.additionAssociative       : [Result] (+4 metadata)
     Natural.tests.additionCommutative       : [Result] (+4 metadata)
     Natural.tests.additionZero              : [Result] (+4 metadata)
     Natural.tests.distributiveLaw           : [Result] (+4 metadata)
     Natural.tests.gen.natural               : '{Gen} Natural (+3 metadata)
     Natural.tests.multiplicationAssociative : [Result] (+4 metadata)
     Natural.tests.multiplicationCommutative : [Result] (+4 metadata)
     Natural.tests.multiplicationZero        : [Result] (+4 metadata)
     Natural.tests.subtractLeftAdjoint       : [Result] (+4 metadata)
     Natural.tests.subtraction               : [Result] (+4 metadata)
     Natural.tests.zeroDivisors              : [Result] (+4 metadata)
     Natural.toDecimalText                   : Natural -> Text (+3 metadata)
     Natural.toDecimalText.doc               : Doc (+3 metadata)
     Natural.toHex                           : Natural -> Text (+3 metadata)
     Natural.toNat                           : Natural -> Optional Nat (+2 metadata)
     Natural.toNat.doc                       : Doc (+2 metadata)
     Natural.toNat.tests.roundtrip           : [Result] (+3 metadata)
     Natural.toText                          : Natural
                                             -> Nat
                                             -> Optional Text (+3 metadata)
     Natural.toText!                         : Natural
                                             -> Nat
                                             ->{Abort} Text (+2 metadata)
     Natural.toText.doc                      : Doc (+3 metadata)
     Natural.zero                            : Natural (+3 metadata)
     Natural.zero.doc                        : Doc (+2 metadata)
     Optional.note                           : e
                                             -> Optional a
                                             ->{Throw e} a (+2 metadata)
     Optional.note.doc                       : Doc (+2 metadata)
     Tuple.bimap                             : (a ->{g} b)
                                             -> (a, a)
                                             ->{g} (b, b) (+2 metadata)
     Tuple.bimap.doc                         : Doc (+2 metadata)
     test.laws.adjoint                       : ∀ o g6 g5 g4 g3 g2 g1 g t.
                                               '{g6} o
                                               -> (o ->{g4} o ->{g5} t)
                                               -> (o ->{g3} o ->{g2} o)
                                               -> (o ->{g1} o ->{g} o)
                                               ->{g6, g5, g4, g3, g2, g1, g} Test (+2 metadata)
     when                                    : Boolean
                                             -> '{e} ()
                                             ->{e} () (+2 metadata)
     when.doc                                : Doc (+2 metadata)

**Comment by pchiusano** [comment] 2021-07-28 16:45
All set, merged in #09jrat6gnn (or is it #e68f00uusd)

This took me forever due to some weird conflicts that I might be starting to understand. 

If I edit a namespace, updating the definitions `foo` and `bar`, and you update the namespace, adding the definition `Natural.toText`, the right behavior is that `foo` and `bar` are the versions I updated, and your (new definition) `Natural.toText` is added in there as well. What I was seeing is that `foo` and `bar` were conflicted in the merged result, and it was keeping your (old) versions of `foo` and `bar` in the namespace. I think it should delete your `foo` and `bar` in this situation.

I'm going to see if I can construct a minimal transcript, but if my theory about what's going on is correct, merge (and by extension, squash) will give terrible results whenever it's not a fast forward and past the LCA there's some updates on one side.

**Closed as completed by pchiusano** 2021-07-28 16:45 UTC
Labels: pull-request

**Comment by pchiusano** [comment] 2021-07-29 18:35
Update is I wasn't able to reproduce the issue according to my theory (https://github.com/unisonweb/unison/pull/2274), so I'm still not sure what was going on here.

**Comment by pchiusano** [comment] 2021-07-29 18:42
Aaron also noted similar problems pulling an updated version of base.

So the two hashes are: #09jrat6gnn (the hash of trunk as of this merged PR) and Aaron hit issues merging into #dfeugrm96l, ~~even though #dfeugrm96l is an ancestor of  #09jrat6gnn and it should just fast forward~~ - disregard, actually, that hash had some updates not in trunk of base.

**Comment by pchiusano** [comment] 2021-08-05 16:01
My current theory is that the namespace from this PR had been pre-squashed, so it had no LCA with trunk and everything was a conflict. It is generally fine to squash a newly added namespace, but squashing the root base namespace is no good. 

I'd like to verify this though, by taking a look at the history of the hashes being merged.

@runarorama does this sound familiar at all?
