### ISSUE TITLE
failing tests for Map.intersectWith

### ISSUE THREAD

**Issue by atacratic** [unisonweb/base#8] opened 2021-06-06 17:44 UTC
I `pull https://github.com/unisonweb/base:.releases._latest .base_v2` while trying out M2, run `test`, and I see a couple of failing tests.

```
  ✗ Map.intersectWith.tests.commutative      
  ✗ Map.intersectWithKey.tests.commutative   
  
  🚫 2 test(s) failing, ✅ 300 test(s) passing
```
tagging @runarorama

**Comment by atacratic** [comment] 2021-06-06 19:54
Turns out this disappears after blowing away and regenerating the test cache, so the fix is probably to do that to the published base library.  `sqlite3 ~/.unison/v2/unison.sqlite3 "delete from watch_result; delete from watch;"` (with the path edited as appropriate) to blow away the cache (take a backup first).

But note that that will instead surface https://github.com/unisonweb/unison/issues/2082 which was previously being masked by the cache.

**Comment by runarorama** [comment] 2021-06-07 00:10
Duplicate of #7

**Closed as completed by runarorama** 2021-06-07 00:10 UTC
